- include_tasks: install_mysql.centos.yml
  when: ansible_distribution == "CentOS"

- include_tasks: install_mysql.redhat.yml
  when: ansible_distribution == "RedHat"

- include_tasks: install_mysql.debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- include_tasks: setup_mysql.yml
- include_tasks: setup_ispyb.yml
