# Provision root permissions for the MariaDB Server
  - name: Create ISPyB database tables
    mysql_db:
      name: "{{ item }}"
      state: present
    with_items:
      -  pydb
      -  pyconfig

# Note: for production use, multiple users with privileges would be required
# This setup is just for development only!
  - name: Setup ISPyB admin user
    mysql_user:
      name: "{{ispyb_db_user}}"
      password: "{{ ispyb_db_password }}"
      state: present
      host: '%'
      priv: '*.*:ALL'

  - name: Reload Privilege Tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False

#
# Import database schema
#
  - name: Import ispyb schema
    mysql_db:
      state: import
      name: "{{ item }}"
      target: "{{ ispyb_home }}/ispyb-ejb/db/{{ item }}.sql"
    with_items:
      - pyconfig
      - pydb
    ignore_errors: True

#
# We could run the ahead scripts here if requied...
# If this is commented out it only imports the sql that has been agreed to be included in the pydb schema
#
  # - name: Find remote sql update files copied
  #   find:
  #     paths: "{{ispyb_home}}/ispyb-ejb/db/scripts/ahead"
  #     patterns: "*.sql"
  #     recurse: "yes"
  #   register: sql_files

  # - name: Import ispyb database updates
  #   mysql_db:
  #     state: import
  #     name: pydb
  #     target: "{{ item.path }}"
  #   with_items:
  #     - "{{ sql_files.files }}"
  #   ignore_errors: True
