  - name: Create ISPyB database tables
    mysql_db:
      name: ispyb
      state: present

  - name: Setup ISPyB admin users
    mysql_user:
      name: "{{ispyb_db_user}}"
      password: "{{ ispyb_db_password }}"
      state: present
      host: '%'
      priv: '*.*:ALL'

  - name: Reload Privilege Tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False

  - name: Checkout ispyb-database schema
    git:
      repo: https://github.com/DiamondLightSource/ispyb-database
      dest: /opt/ispyb-database
    ignore_errors: True

  - name: Import ispyb schema file(s)
    mysql_db:
      state: import
      name: ispyb
      target: "{{ item }}"
    with_items:
      - /opt/ispyb-database/schema/tables.sql
      - /opt/ispyb-database/schema/routines.sql
    ignore_errors: True
