# Provision root permissions for the MariaDB Server
  - name: Create ISPyB database tables
    mysql_db:
      name: "{{ item }}"
      state: present
    with_items:
      -  ispyb_config
      -  ispyb_db
      -  pydb
      -  pyconfig

  - name: Setup ISPyB users
    mysql_user:
      name: "{{ item }}"
      password: "{{ ispyb_db_password }}"
      state: present
      host: localhost
      priv: '*.*:ALL'
    with_items:
      - ispyb_config
      - ispyb_db
      - pxuser

  - name: Setup ISPyB admin users
    mysql_user:
      name: "{{ item }}"
      password: "{{ ispyb_db_password }}"
      state: present
      host: '%'
      priv: '*.*:ALL'
    with_items:
      - "{{ispyb_db_user}}"



  - name: Reload Privilege Tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False

#
# Import database schema
#
#
  - name: Import ispyb schema
    mysql_db:
      state: import
      name: "{{ item }}"
      target: "{{ ispyb_home }}/ispyb-ejb/db/{{ item }}.sql"
    with_items:
      - pyconfig
      - pydb
    ignore_errors: True

# As we are running from the trunk - run the ahead scripts as well
  - name: Find remote sql update files copied
    find:
      paths: "{{ispyb_home}}/ispyb-ejb/db/scripts/ahead"
      patterns: "*.sql"
      recurse: "yes"
    register: sql_files

  - name: Import ispyb database updates
    mysql_db:
      state: import
      name: pydb
      target: "{{ item.path }}"
    with_items:
      - "{{ sql_files.files }}"
    ignore_errors: True
